ingress-nginx:
  controller:
    ingressClassResource:
      name: ext-nginx
      enabled: true
      default: false
      controllerValue: k8s.io/ext-ingress-nginx
    ingressClass: ext-nginx
    scope:
      enabled: true
      namespace: external
    replicaCount: 1
    minAvailable: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 300
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 300
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.13.92
      externalTrafficPolicy: Local
