apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:willyhutw/microlab.git'
    targetRevision: HEAD
    path: argocd/internal/data-pipeline
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
