apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-resources
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/grafana/resources
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
