apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hubble
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/hubble
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
        releaseName: cilium
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/hubble/resources
      targetRevision: HEAD
  destination:
    name: micro
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
