apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-igw-external
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/istio-igw-external
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
        releaseName: istio-igw-external
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
