apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/loki
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
        releaseName: loki
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/loki/resources
      targetRevision: HEAD
  destination:
    name: micro
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
