apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-snmp-exporter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/prometheus-snmp-exporter
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
        releaseName: prometheus-snmp-exporter
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      path: argocd/internal/prometheus-snmp-exporter/resources
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
