apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: willyhutw
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:willyhutw/microlab.git'
    path: argocd/internal/willyhutw
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
