apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: data
spec:
  storageClassName: local-storage
  volumeName: postgresql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
