apiVersion: v2
name: istio-base
description: A Helm chart depends on istio-base.
type: application
version: 1.29.2
appVersion: 1.29.2
dependencies:
  - name: base
    version: 1.29.2
    repository: https://istio-release.storage.googleapis.com/charts
