apiVersion: v1
kind: Service
metadata:
  name: data-entry
  namespace: monitoring
  labels:
    app: data-entry
  annotations:
    lbipam.cilium.io/ips: 192.168.12.97
spec:
  type: LoadBalancer
  selector:
    app: data-entry
  ports:
    - port: 5140
      protocol: UDP
      targetPort: 5140
