loki:
  test:
    enabled: false
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  singleBinary:
    replicas: 1
    resources: {}
    terminationGracePeriodSeconds: 30
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - micro-node-1
    persistence:
      enabled: false
      enableStatefulSetAutoDeletePVC: false
    extraVolumeMounts:
      - name: storage
        mountPath: /var/loki
    extraVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki
  deploymentMode: SingleBinary
  loki:
    podLabels: {}
    useTestSchema: true
    testSchemaConfig:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    enableServiceLinks: false
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      http_server_read_timeout: 180s
      http_server_write_timeout: 180s
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      query_timeout: 120s
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1
    storage:
      type: filesystem
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
  chunksCache:
    enabled: false
  gateway:
    enabled: false
  lokiCanary:
    enabled: false
  resultsCache:
    enabled: false
  ingress:
    enabled: false
