apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-filter-pfsense
  namespace: monitoring
  labels:
    app: data-filter-pfsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-filter-pfsense
  template:
    metadata:
      labels:
        app: data-filter-pfsense
    spec:
      containers:
        - name: data-filter-pfsense
          image: public.ecr.aws/k1l6o6j1/fluentd:20250209
          env:
            - name: LD_PRELOAD
              value: ""
          resources: {}
          ports:
            - containerPort: 24225
          volumeMounts:
            - mountPath: /fluentd/etc
              name: config
      volumes:
        - name: config
          configMap:
            name: data-filter-pfsense
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - tinylab-node-1
