apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart depends on kube-prometheus-stack.
type: application
version: 84.5.0
appVersion: v0.90.1
dependencies:
  - name: kube-prometheus-stack
    version: 84.5.0
    repository: https://prometheus-community.github.io/helm-charts
