apiVersion: v2
name: hubble
description: A Helm chart depends on cilium (hubble).
type: application
version: 1.17.4
appVersion: 1.17.4
dependencies:
  - name: cilium
    version: 1.17.4
    repository: https://helm.cilium.io
