apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: loki-gateway
  namespace: monitoring
spec:
  selector:
    istio: ingressgateway
    igw-type: internal
  servers:
    - port:
        number: 3000
        name: loki
        protocol: TCP
      hosts:
        - loki.willyhu.tw
