apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: ai
spec:
  storageClassName: local-storage
  volumeName: open-webui
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
