apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant
  namespace: ai
spec:
  storageClassName: local-storage
  volumeName: qdrant
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
