# https://artifacthub.io/packages/helm/grafana/grafana
grafana:
  replicas: 1
  createConfigmap: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - micro-node-1
  ingress:
    enabled: false
  persistence:
    enabled: true
    existingClaim: grafana
