istio_namespace: "istio-system"
auth:
  strategy: "anonymous"
deployment:
  view_only_mode: true
external_services:
  prometheus:
    url: http://prometheus-server.monitoring.svc.cluster:9090
server:
  port: 20001
  observability:
    metrics:
      enabled: false
