istio_namespace: "istio-system"
auth:
  strategy: anonymous
deployment:
  view_only_mode: true
external_services:
  custom_dashboards:
    enabled: false
server:
  port: 20001
  observability:
    metrics:
      enabled: false
