apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: 'https://langfuse.github.io/langfuse-k8s'
      chart: langfuse
      targetRevision: 1.5.30
      helm:
        releaseName: langfuse
        valueFiles:
          - $langfuse-values/argocd/internal/langfuse/values.yaml
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      targetRevision: HEAD
      ref: langfuse-values
    - repoURL: 'git@github.com:willyhutw/microlab.git'
      targetRevision: HEAD
      path: argocd/internal/langfuse/resources
  destination:
    name: micro
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
