auths:
  public_v1:
    version: 1
  public_v2:
    version: 2
modules:
  pfsense:
    walk:
      - 1.3.6.1.2.1.2 # MIB2::interfaces
      - 1.3.6.1.2.1.31.1 # MIB2::ifMIB::ifXTable
      - 1.3.6.1.4.1.2021.4 # UCD(ucdavis)::memory
      - 1.3.6.1.4.1.2021.9 # UCD(ucdavis)::disk
      - 1.3.6.1.4.1.2021.10 # UCD(ucdavis)::loadAverage
      - 1.3.6.1.4.1.2021.11 # UCD(ucdavis)::cpu
      - 1.3.6.1.4.1.2021.8 # UCD(ucdavis)::extend
      - 1.3.6.1.4.1.12325.1.200.1.1 # BEGEMOT-PF-MIB::pfStatus
      - 1.3.6.1.4.1.12325.1.200.1.8 # BEGEMOT-PF-MIB::pfInterface
      - 1.3.6.1.4.1.12325.1.200.1.11 # BEGEMOT-PF-MIB::pfLabels
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
      - source_indexes: [pfInterfacesIfIndex]
        lookup: pfInterfacesIfDescr
      - source_indexes: [pfLabelsLblIndex]
        lookup: pfLabelsLblName
      - source_indexes: [extIndex]
        lookup: extNames
    overrides:
      ifAlias:
        ignore: true
      ifDescr:
        ignore: true
      ifName:
        ignore: true
      ifType:
        type: EnumAsInfo
      pfInterfacesIfDescr:
        ignore: true
        type: DisplayString
      pfLabelsLblName:
        ignore: true
        type: DisplayString
      pfLogInterfaceName:
        ignore: true
        type: DisplayString
      extOutput:
        regex_extracts: # transform DisplayString to gauge
          '':
            - regex: '([0-9.]+)'
              value: $1
