apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ai
spec:
  storageClassName: local-storage
  volumeName: ollama
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
