{
 "title": "Access - willyhutw",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (count_over_time({service_name=\"willyhutw-access\"} [$__auto]))",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source_country_code) (count_over_time({service_name=\"willyhutw-access\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "TOP 5 Source Country",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(source_country) (count_over_time({service_name=\"willyhutw-access\"} [$__auto])))"
    }
   ]
  },
  {
   "title": "TOP 5 Request",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(request) (count_over_time({service_name=\"willyhutw-access\"} [$__auto])))"
    }
   ]
  },
  {
   "title": "TOP 5 Referer",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(http_referer) (count_over_time({service_name=\"willyhutw-access\"} [$__auto])))"
    }
   ]
  },
  {
   "title": "TOP 5 User Agent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(http_user_agent) (count_over_time({service_name=\"willyhutw-access\"} [$__auto])))"
    }
   ]
  },
  {
   "title": "Non-Bot",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"willyhutw-access\", http_user_agent!~\".*(bot|Bot|BOT).*\"}  | line_format \"[{{.source_country}}] {{.real_ip}} {{.http_referer}} -> {{.http_version}} {{.method}} {{.status}} {{.request}} {{.http_user_agent}}\""
    }
   ]
  },
  {
   "title": "Bot",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"willyhutw-access\", http_user_agent=~\".*(bot|Bot|BOT).*\"}  | line_format \"[{{.source_country}}] {{.real_ip}} {{.http_referer}} -> {{.http_version}} {{.method}} {{.status}} {{.request}} {{.http_user_agent}}\""
    }
   ]
  },
  {
   "title": "llms.txt",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 46 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"willyhutw-access\", request=~\"/(llms|llms-full).txt\"}  | line_format \"[{{.source_country}}] {{.real_ip}} {{.http_referer}} -> {{.http_version}} {{.method}} {{.status}} {{.request}} {{.http_user_agent}}\""
    }
   ]
  }
 ]
}