{
 "title": "Node",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (node)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (sum(node_memory_MemAvailable_bytes) by (node) / sum(node_memory_MemTotal_bytes) by (node))) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "max(node_filesystem_avail_bytes) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "max((node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 /(node_filesystem_avail_bytes + (node_filesystem_size_bytes - node_filesystem_free_bytes))) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(rate(node_disk_reads_completed_total[$interval])) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total[$interval])) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "max(rate(node_disk_writes_completed_total[$interval])) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total[$interval])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(node_netstat_Tcp_CurrEstab) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total[$interval])) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "avg(rate(node_network_transmit_bytes_total[$interval])) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "max(node_sockstat_TCP_tw) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}