{
 "title": "pfSense - Firewall - Block (LAN)",
 "tags": [
  "pfSense",
  "FilterLog"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "interface",
    "query": {}
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(action) (count_over_time({log_type=\"filterlog\", real_interface=\"$interface\", action=\"block\"} [$__auto]))",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "TOP 3 Protocol",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "topk(3, sum by(protocol_text) (count_over_time({log_type=\"filterlog\", real_interface=\"$interface\", action=\"block\"} [$__auto])))"
    }
   ]
  },
  {
   "title": "TOP 10 Source -> Destination",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "topk(10, sum by(source_address, destination_address, destination_country) (count_over_time({log_type=\"filterlog\", real_interface=\"$interface\", action=\"block\"} [$__auto])))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 4 },
   "targets": [
    {
     "expr": "{log_type=\"filterlog\", real_interface=\"$interface\", action=\"block\"}  | line_format \"| {{.source_address}} -> {{.protocol_text | upper}}{{if eq `tcp` .protocol_text}}:{{.tcp_flags}}{{end}} -> {{.destination_address}}{{if or (eq `tcp` .protocol_text) (eq `udp` .protocol_text)}}:{{.destination_port}}{{end}}{{if ne `null` .destination_country}} [{{.destination_country}}]{{end}}\""
    }
   ]
  },
  {
   "title": "TOP 5 Port (<1024)",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, sum by(destination_port) (count_over_time({log_type=\"filterlog\", real_interface=\"$interface\", action=\"block\"} | destination_port < 1024 [$__auto])))"
    }
   ]
  }
 ]
}