{
 "title": "pfSense - Firewall - Block (WAN)",
 "tags": [
  "pfSense",
  "FilterLog"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(action) (count_over_time({log_type=\"filterlog\", real_interface=\"pppoe0\", action=\"block\"} [$__auto]))",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(source_country_code) (count_over_time({log_type=\"filterlog\", real_interface=\"pppoe0\", action=\"block\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "TOP 3 Protocol",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(3, sum by(protocol_text) (count_over_time({log_type=\"filterlog\", real_interface=\"pppoe0\", action=\"block\"} [$__auto])))"
    }
   ]
  },
  {
   "title": "TOP 10 Address",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by(source_address, source_country) (count_over_time({log_type=\"filterlog\", real_interface=\"pppoe0\", action=\"block\"} [$__auto])))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 12, "w": 14, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "{log_type=\"filterlog\", real_interface=\"pppoe0\", action=\"block\"}  | line_format \"[{{.source_country}}] {{.source_address}} -> {{.protocol_text | upper}}{{if eq `tcp` .protocol_text}}:{{.tcp_flags}}{{end}} -> {{.destination_address}}:{{.destination_port}} [{{.destination_country}}]\""
    }
   ]
  },
  {
   "title": "TOP 5 Port (<1024)",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(5, sum by(destination_port) (count_over_time({log_type=\"filterlog\", real_interface=\"pppoe0\", action=\"block\"} | destination_port < 1024 [$__auto])))"
    }
   ]
  }
 ]
}